Avoid updating clap to 4.1.x
it does not support wasi without nightly

```console
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.8/src/lib.rs:20:33
   |
20 | #![cfg_attr(target_os = "wasi", feature(thread_local))]
   |
```